# Custom Language File for Launcher Customizer

[ejs.app]
title = "Milleria"

[ejs.landing]
mediaGitHubURL = "https://github.com/KingTatouille/Milleria-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/milleria"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR MILLERIA"
welcomeDescription = "C'est ici que vous retrouverez l'envie de jouer à Minecraft."
welcomeDescCTA = "Vous êtes presque sur le serveur !"
